openimis/openimis-be-social_protection_py

.github/workflows/openmis-module-test.yml
social_protection/schema.py

Ticket: [CM-29](https://github.com/openimis/openimis-be-core_py/pull/183)
Requires [core change merge](https://github.com/openimis/openimis-be-core_py/pull/183)
[CM-29]: https://openimis.atlassian.net/browse/CM-29?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ

CM-29: Added generic export

---

social_protection/schema.py

https://openimis.atlassian.net/browse/CM-105

CM-105: add export group beneficiary

---

social_protection/tests/beneficiary_service_test.py

This PR changes import name to match a new one in Individual module from this pr: https://github.com/openimis/openimis-be-individual_py/pull/3
https://openimis.atlassian.net/browse/CM-113

CM-113: change import name

---

social_protection/schema.py

https://openimis.atlassian.net/browse/CM-108
It needs: 
https://github.com/openimis/openimis-fe-individual_js/pull/10
https://github.com/openimis/openimis-fe-social_protection_js/pull/16
https://github.com/openimis/openimis-be-individual_py/pull/4

CM-108: update schema for group detail view

---

social_protection/custom_filters.py
social_protection/schema.py

TICKET: https://openimis.atlassian.net/browse/CM-162

CM-162: applying improvements into applying custom filters

---

social_protection/services.py
social_protection/urls.py
social_protection/views.py

[https://openimis.atlassian.net/browse/CM-19](https://openimis.atlassian.net/browse/CM-19)
Changes:
- Added `BeneficiaryImportService`
- Added `import_beneficiaries` endpoint

CM-19 Create an endpoint for "Beneficiary" import using unstructured CSV/XLSX files

---

social_protection/services.py

Changes in types due to schema requirements. User uuid changed to align with requiements of userCreate and userUpdate fields.

CM-11: Change JSON type, add atomic to seerice

---

social_protection/apps.py
social_protection/gql_mutations.py
social_protection/services.py
social_protection/signals.py
social_protection/validation.py

[https://openimis.atlassian.net/browse/CM-206](https://openimis.atlassian.net/browse/CM-206)

CM-206 Create BenefitPlan Update Task Contribution BE

---

social_protection/apps.py

[https://openimis.atlassian.net/browse/CM-188](https://openimis.atlassian.net/browse/CM-188)

CM-188 Adjusted backend for social protection

---

.github/workflows/openmis-module-test-psql.yml
.github/workflows/openmis-module-test.yml

Added PostgreSQL engine test execution.

CM-235: Added PostgreSQL engine test execution.

---

social_protection/gql_mutations.py

Make beneficiary status required in mutation.

hotfix-status-required: make beneficiary status required

---

social_protection/gql_queries.py

https://openimis.atlassian.net/browse/CM-288
This PR fixes situation when user with rights to see benefit plans but with no rights to see schema, couldn't see benefit plans.

CM-288: fix benefit plan displaying

---

social_protection/custom_filters.py

https://openimis.atlassian.net/browse/CM-296
This PR updates how benefit plan custom filter implementation determines available filters.

CM-296: update custom filters implementation in social protection

---

social_protection/gql_queries.py

This PR fixes permission check for some fields in benefit plan gql.

fix permission check

---

social_protection/schema.py

https://openimis.atlassian.net/browse/CM-334

CM-334: use search to filter benefitplans

---

social_protection/gql_queries.py
social_protection/schema.py

https://openimis.atlassian.net/browse/CM-359

CM-359: get beneficiary_data_schema instead of json_ext

---

social_protection/services.py

https://openimis.atlassian.net/browse/CM-458
Due to changes in serializing task data there was a need to adjust existing serializers.
It needs: https://github.com/openimis/openimis-be-tasks_management_py/pull/37

CM-458: adjust task display

---

social_protection/gql_mutations.py

This reverts commit 5eafd83ff7acaa679fab3a6c614c364185b69a40.

Revert "test-branch"

---

locale/en/LC_MESSAGES/django.po
setup.py
social_protection/schema.py
social_protection/validation.py

https://openimis.atlassian.net/browse/CM-497
It needs: https://github.com/openimis/openimis-be-core_py/pull/254

CM-497: move schema validation to core

---

social_protection/signals/__init__.py
social_protection/signals/on_confirm_enrollment_of_individual.py

TICKET: https://openimis.atlassian.net/browse/CM-710

CM-710: Backend Development for Program Selection and Filter Application

---

social_protection/apps.py
social_protection/urls.py
social_protection/views.py

https://openimis.atlassian.net/browse/CM-700
It needs: https://github.com/openimis/openimis-be-core_py/pull/267

CM-700: download upload file

---

social_protection/gql_queries.py

https://openimis.atlassian.net/browse/CM-766

CM-766: check if benefit plan has payment plans

---

social_protection/gql_queries.py
social_protection/schema.py

TICKET: https://openimis.atlassian.net/browse/CM-767

CM-767: added changelog on backend side for programme

---

social_protection/services.py
social_protection/workflows/base_beneficiary_update.py
social_protection/workflows/base_beneficiary_upload.py
social_protection/workflows/beneficiary_update_valid.py
social_protection/workflows/beneficiary_upload_valid.py

https://openimis.atlassian.net/browse/CM-852

CM-852: fixed synch with opensearch for benefitplan beneficiary upload

---

social_protection/workflows/base_beneficiary_update.py
social_protection/workflows/beneficiary_update_valid.py

https://openimis.atlassian.net/browse/CM-852

CM-852: added missing json_ext update on individual level

---

social_protection/apps.py
social_protection/signals/on_confirm_enrollment_of_individual.py
social_protection/signals/on_validation_import_valid_items.py
social_protection/utils.py

https://openimis.atlassian.net/browse/CM-712

CM-712: added enrollment validation through task management

---

social_protection/signals/on_validation_import_valid_items.py
social_protection/workflows/beneficiary_upload_valid.py

TICKET: https://openimis.atlassian.net/browse/CM-719

CM-719: fixed bulk import for beneficiaries - atomic task resolution

---

social_protection/signals/on_validation_import_valid_items.py
social_protection/workflows/beneficiary_upload_valid.py

MERGING develop into release/24.04

MERGING develop into release/24.04

---

social_protection/services.py
social_protection/views.py

https://openimis.atlassian.net/browse/CM-808

CM-808: aggregation by column

---

social_protection/export_mixin.py
social_protection/gql_queries.py
social_protection/schema.py

https://openimis.atlassian.net/browse/CM-819

CM-819: added adjustments to support download with custom filters for group beneficiaires

---

social_protection/schema.py

part of ticket: https://openimis.atlassian.net/browse/CM-820
- added missing lookup on queryset level for benefit plan when individual is added as argument

CM-820: added missing relations lookup - individuals for group benefit plans

---

social_protection/apps.py
social_protection/gql_mutations.py
social_protection/schema.py
social_protection/services.py
social_protection/signals/__init__.py

TICKET: https://openimis.atlassian.net/browse/CM-909

CM-909: added possibility to suspend a programme
